const data = {
    products:[
        {
            _id:'1',
            name:'Currents - Tame Impala',
            category:'Psychedelic Rock',
            image:'/images/p1.png',
            price:34.99,
            brand:'',
            rating:4.5,
            numReview:0,
            description:'',
        },
        {
            _id:'2',
            name:'how i\'m feeling now - Charli XCX',
            category:'Eletronic Pop',
            image:'/images/p2.png',
            price:38.99,
            brand:'',
            rating:4,
            numReview:0,
            description:'',
        },
        {
            _id:'3',
            name:'Pure Heroine - Lorde',
            category:'Indie Pop',
            image:'/images/p3.png',
            price:63.99,
            brand:'',
            rating:5,
            numReview:0,
            description:'',
        },
        {
            _id:'4',
            name:'Nightride - Tinashe',
            category:'R&B',
            image:'/images/p4.png',
            price:25.00,
            brand:'',
            rating:4,
            numReview:0,
            description:'',
        },
    ],
};
export default data;